joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

left_wheel_effort_controller:
  type: "effort_controllers/JointEffortController"
  joint: left_wheel_joint

right_wheel_effort_controller:
  type: "effort_controllers/JointEffortController"
  joint: right_wheel_joint

/gazebo_ros_control/pid_gains:
  left_wheel_joint: {p: 10.0, i: 0.1, d: 1.0}
  right_wheel_joint: {p: 10.0, i: 0.1, d: 1.0}